# Generated by Django 5.2.14 on 2026-06-16 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_visitante'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('capacidad_puestos', models.PositiveIntegerField()),
                ('tiene_conexion_electrica', models.BooleanField(default=False)),
                ('feria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sectores', to='app.feria')),
            ],
        ),
    ]
